name: recetox-aplcms
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >= 3.5
  - r-pkgload <= 1.2.4
  - r-devtools
  - r-biocmanager
  - r-mass
  - r-rgl
  - bioconductor-mzR
  - r-splines2
  - r-doparallel
  - r-foreach
  - r-iterators
  - r-snow
  - r-gbm
  - r-e1071
  - r-randomForest
  - r-rocr
  - r-rocs
  - r-rcpp
  - r-arrow <= 8.0.0
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-datacomparer
  - r-tibble
  - r-languageserver
  - r-jsonlite
  - r-styler
  - r-datacomparer
  - r-patrick
  - radian
  - r-httpgd
