# This is a basic workflow to help you get started with Actions

name: R Conda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: recetox-aplcms
          auto-update-conda: true
          environment-file: conda/environment-dev.yaml
          auto-activate-base: false
      - run: |
          conda init bash
          conda env list
      - name: Fetch adjusted test data
        run: wget -P tests/testdata/adjusted -i tests/remote-files/adjusted.txt
      - name: Fetch aligned test data
        run: wget -P tests/testdata/aligned -i tests/remote-files/aligned.txt
      - name: Fetch extracted test data
        run: wget -P tests/testdata/extracted -i tests/remote-files/extracted.txt
      - name: Fetch input test data
        run: wget -P tests/testdata/input -i tests/remote-files/input.txt
      - name: Fetch recovered test data
        run: wget -P tests/testdata/recovered -i tests/remote-files/recovered.txt
      - name: Fetch recovered-extracted test data
        run: wget -P tests/testdata/recovered/recovered-extracted -i tests/remote-files/recovered-extracted.txt
      - name: Fetch recovered-corrected test data
        run: wget -P tests/testdata/recovered/recovered-corrected -i tests/remote-files/recovered-corrected.txt
      - name: Fetch filtered test data
        run: wget -P tests/testdata/filtered -i tests/remote-files/filtered.txt
      - name: Fetch features test data
        run: wget -P tests/testdata/features -i tests/remote-files/features.txt
      - name: Fetch clusters test data
        run: wget -P tests/testdata/clusters -i tests/remote-files/clusters.txt
      - name: Fetch features test data
        run: wget -P tests/testdata/hybrid -i tests/remote-files/hybrid.txt
      - name: Run devtools::check()
        run: |
          conda activate recetox-aplcms
          Rscript -e "devtools::check('.', error_on = 'error')"
